version: '3.8'
services:
  flowers-app:
    build: .
    container_name: flowers-recognition
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
